### ISSUE TITLE
数据库配置问题

### ISSUE THREAD

**Issue by shiguangbiyi** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#10]

**Comment by VictorHuu** [comment]
在行 352 上开始执行命令时出错:
```sql
CREATE OR REPLACE DIRECTORY my_dir AS 'D:/Desktop';--将D:/Desktop转化为存储图片的路径
GRANT READ, WRITE ON DIRECTORY my_dir TO c##pet;
```
按照README的指南，将存储文件的路径替换为自己想要的路径

381行做相应修改：
```
src_bfile := BFILENAME('MY_DIR', 'picture' || TO_CHAR(ROUND(DBMS_RANDOM.value(1, 3), 0)) || '.png'); -- modify 'MY_DIR' and 'my_file.jpg' accordingly
```
上述代码要求图片文件名为picture1~3.png，可以自己指定。

***由于sqladoption.sql代码太长，因此今后建议移步至PetFosterInit的C#文件通过配置JSON与XML进行数据库配置，本sql代码的独特作用为生成随机数据以供测试。***

**Comment by VictorHuu** [comment]
# NOTICE
以后移步至 https://github.com/VictorHuu/PetFosterInit 仓库,下载最新的发行版本！
