### ISSUE TITLE
前后端交互的问题

### ISSUE THREAD

**Issue by aodef** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#11]
const fetchData = async () => {
  try {
    let response
    if (selectedTag.value === '全部') {
      // Fetch all data
      response = await axios.get('/api/all-records')
    } else if (selectedTag.value === '记录') {
      // Fetch records data
      response = await axios.get('/api/records')
    } else if (selectedTag.value === '申请') {
      // Fetch applications data
      response = await axios.get('/api/applications')
    }
    tableData.value = response.data
  } catch (error) {
    console.error('Error fetching data:', error)
  }
}
想请问一下后端的同学，就是我想要获取两个数据表中的数据，通过'/api/all-records'获取，这个对后端来说可以吗？

**Comment by aodef** [comment]
interface FosterRecord {
  date: string
  petId: string
  userId: string
  days: number
  tag: string
}并且获取的数据要加一个tag值，显示是哪一个数据表的值，请问这个方便实现吗？如果不方便的话我就和前端同学协商取消全部这个选项，只留记录和申请，就可以分别获取了

**Comment by aodef** [comment]
再请问一下，就是新增加的表示状态的数据是什么数据类型呀？值分别是什么？

**Comment by VictorHuu** [comment]
- 针对第三个问题，看commit与diff，说的很清楚。

[历史记录](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/commits/main/Database)

- 点击上述网页的最近几次带issue标签的提交记录，可以查看改动。

- 在issue #6 与 #9 中也说的很详细了。

**Comment by aodef** [comment]
okok,还不太会用这个，第三个问题明白了，麻烦你了

**Comment by VictorHuu** [comment]
> 并且获取的数据要加一个tag值，显示是哪一个数据表的值，请问这个方便实现吗？

"哪一个数据表",那么有几种可能的数据表呢？画出对应的流程图，便于我理解，然后**增加一个tag很容易（但是我建议改名叫datasrc，因为tag表示Git中的版本，易混淆）**，并且可以做到不污染数据访问层（**只涉及BLL层**）。

> 只留记录和申请，就可以分别获取了

这句话中的记录和申请是什么意思?

P.S.：Issue提问要尽可能易懂。第一个问题由 @asceking 回答。

**Comment by aodef** [comment]
数据表指的是foster和comment_pet表
申请和记录就对应的是foster表中的数据和comment_pet表中的数据

**Comment by asceking** [comment]
第一个是问api可以含“-”这个字符吗？完全可以的。

**Comment by aodef** [comment]
第一个是指单一接口获取两个表的数据

**Comment by aodef** [comment]
![流程图](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/119112957/cef9eb5b-da49-4df4-947d-9d54844764de)

**Comment by VictorHuu** [comment]
>
 ```js
interface FosterRecord {
date: string
petId: string
userId: string
days: number
tag: string
}
```
> 并且获取的数据要加一个tag值，显示是哪一个数据表的值，请问这个方便实现吗？如果不方便的话我就和前端同学协商取消全部这个选项，只留记录和申请，就可以分别获取了

**针对你的原问题，该方案很容易实现**
但：
- comment_pet是对**宠物评论**的意思
-  我找不到comment_pet与foster在业务逻辑上有的共同点，**所以需要指出来共同点**。
- 一般来说，如果一个网站评论宠物都需要审核那么这个网站也太可怕了，申请和发帖需要审核还差不多。
- comment_pet与like_pet与collect_pet_info可以归为一类，表示宠物的social statistics
- foster,accommodate,adopt可以归为一类，表示宠物的所有权。

**Comment by asceking** [comment]
> 第一个是指单一接口获取两个表的数据

不好意思，我的问题（捂脸）

这个也可以的，没问题的

两个一起的话数据返回过来可能长这样（就是类似嵌套的样子）（拿gpt生成的例子）：
`{
  "records": [
    {
      "id": 1,
      "name": "Record 1",
      "description": "This is record 1"
    },
    {
      "id": 2,
      "name": "Record 2",
      "description": "This is record 2"
    }
  ],
  "applications": [
    {
      "id": 1,
      "name": "Application 1",
      "status": "Pending"
    },
    {
      "id": 2,
      "name": "Application 2",
      "status": "Approved"
    }
  ]
}
`

**Comment by aodef** [comment]
没事没事，我和前端同学讨论了一下，决定直接取消对评论的审核，简单处理。

**Comment by aodef** [comment]
麻烦你们啦
