### ISSUE TITLE
数据库用户地址问题

### ISSUE THREAD

**Issue by shiguangbiyi** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#14]
现在弄清楚地址（user2表下的adress）是指某个城市还是家庭住址
如果是城市的话那就是全国连锁，全国连锁为了寄养领养方便就会涉及宠物的位置，又是一层逻辑，还是说不连锁，邮寄？
如果是家庭住址的话那就简单点了，不用涉及更多的地址逻辑。

**Comment by VictorHuu** [comment]
上海市还是同济大学？如果是上海市，那么自提也行，按区与街道两级，如果是同济大学，那么就是校区-宿舍楼-门牌号，还是自提吧，因为再小范围的邮寄都麻烦。

**Comment by shiguangbiyi** [comment]
所以说表中的address填入的是什么？城市还是具体地址

**Comment by VictorHuu** [comment]
当前是省+市

**Comment by shiguangbiyi** [comment]
那现在这个address暂无实质业务逻辑作用了，后续再看吧
