### ISSUE TITLE
医疗与捐款功能

### ISSUE THREAD

**Issue by VictorHuu** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#16]
这是初步的接口介绍：
- 医疗界面：
预约表页面：用户输入宠物姓名{宠物姓名}、宠物种类、{宠物种类（猫、狗）}、预约时间{预约时间}、病情描述{病情描述}
- 捐款界面：
捐款表：用户输入捐款金额

@M2030123 涉及到的表有treatment,pet.
预约表界面:应该对应的是appointment表，species显然是宠物种类，这个我会马上修改。
修改完之后，完成对应的DAL与BLL，视图我也会在数据库层设计好。

@asceking 完成对应的axios部分

@llRagdoll 之后可能的功能完善与后端完成之后进行测试
考虑到医疗界面会涉及到新宠物和旧宠物的问题，如果用户选择已有宠物，那么可以考虑一下输入宠物名，下拉框里面有宠物的肖像，ID与名字，或者直接输入ID。新的宠物就是你之前说的流程

**Comment by llRagdoll** [comment]
医生表是否可以增加照片属性呢？我在医疗界面想展示医生照片~ @VictorHuu

**Comment by VictorHuu** [comment]
@llRagdoll 可以，每人一张

**Comment by VictorHuu** [comment]
@llRagdoll 医生vet表的字段是什么样的

**Comment by llRagdoll** [comment]
@VictorHuu 我们的医生应该是全科的，所以在预约时候增加所有医生的选项让用户选择嘛

**Comment by VictorHuu** [comment]
@llRagdoll 预约表要传兽医的vet_id

**Comment by llRagdoll** [comment]
@VictorHuu OK，已更新界面和api

**Comment by VictorHuu** [comment]
@asceking 今天写医疗和捐款

**Comment by VictorHuu** [comment]
现在，个人与管理员捐赠显示，捐赠，预约新旧宠物，医生管理员端与选项显示，旧有宠物显示全部完成！
