### ISSUE TITLE
个人页面点赞量和阅读量数据需求

### ISSUE THREAD

**Issue by shiguangbiyi** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#17]
![image](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/126951839/fc8abe59-9a3f-4810-b946-cc34bcb0a9d3)
这个点赞量和阅读量，分别需要后端计算该用户发的帖子的点赞量和阅读量的总和，用json形式打包。
接口路由：/api/likeandread

**Comment by VictorHuu** [comment]
点赞量是所有帖子的点赞量吧，单个帖子点赞量由数据库触发器自动计算，多个帖子创个视图的事情。json打包交给 @asceking

**Comment by VictorHuu** [comment]
@shiguangbiyi 这是初步的数据库视图样式：

![image](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/103842499/fb9ecc0f-0ff6-4289-a1d6-737085a4ef03)

**Comment by VictorHuu** [comment]
The issue has been resolved with this commit :https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/commit/7744e7a8261b03305e52f2fc1279c8bdf4ff2c1b
