### ISSUE TITLE
一些网页测试的问题

### ISSUE THREAD

**Issue by VictorHuu** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#51]
- [x] #52
- [x] #53
- [x] 匿名用户登陆管理员界面
![image](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/103842499/e558c7fe-0147-40d3-abf4-b910b0a82380)
- [ ] #54
- [x] 公告的对话框展示需要像编辑框TextBox一样是富文本 @llRagdoll 
- [x] 未登录的用户不能评论，设置成静态输入框或者评论框直接消失吧 @DaenerysTar

**Comment by DaenerysTar** [comment]
收到
