### ISSUE TITLE
审核相关问题

### ISSUE THREAD

**Issue by shiguangbiyi** [shiguangbiyi/DataBase_Program_Pet-Rescue-Station#6]
关于审核的流程，前端同学提出的流程是：寄养和捐款页面数据传输时，应先给审核界面传送数据，再由审核界面向数据库传送；还是寄养和捐款页面传输数据给数据库，数据库给审核界面，再由审核界面传输信息给数据库。正确流程应该是后者？ @VictorHuu @asceking

**Comment by VictorHuu** [comment]
后者：更新待审核数据前端->后端->数据库;审核数据:从数据库取数据审核，依然是前端->后端->数据库。因为考虑到即使是待审核数据，也是需要持久存储的，审核需要确保任意时间均可查看待审核数据。
## 区分待审核信息与通过审核信息
考虑数据库增加一个数据censor_status，有to be censored,abored,legitimate三种状态，是否需要补充？或者其他方案？

**Comment by VictorHuu** [comment]
@shiguangbiyi 
1. 如果需要审核那么是否需要必要的文字信息？
2. 寄养对应
- adopt 终身领养
-  foster 临时抚养
-  accommodate 临时在救助中心寄养
上述三者的哪一个？
以下是对应的Oracle SQL代码：
```sql
ALTER TABLE donation
ADD censor_state VARCHAR2(20) default 'to be censored'; 

ALTER TABLE donation
ADD CONSTRAINT check_censor_state CHECK (censor_state IN ('to be censored', 'aborted', 'legitimate'));
ALTER TABLE accommodate--如果是foster/adopt更改表明即可。
ADD censor_state VARCHAR2(20) default 'to be censored' CHECK (censor_state IN ('to be censored', 'aborted', 'legitimate')); 
```
3. 关于application对应的事务逻辑，**请务必认真讨论，最好画出流程图**，理想的方案是：

- 只需要application增加censor_state,
- 在缩减一些冗余信息的前提下，
- 各种需要审核的信息首先经过application与其他各种表join后的视图查看（依据category区分类型）并进行审核。

**Comment by shiguangbiyi** [comment]
1.审核流程都是人工审核，不需要文字信息
2.accomodate
3.领养，寄养的审核只需查看用户信息即可，如果想增加事务逻辑的话可以考虑join，到时候就看方不方便还有实现后逻辑是否丰富

**Comment by shiguangbiyi** [comment]
![审核流程（全流程通用）](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/126951839/d08b42e9-1abd-4bc5-9726-3848df84b9e4)
